server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # handle API behind /sip-calc
    location /sip-calc/api/ {
        rewrite ^/sip-calc/api/(.*)$ /api/$1 break;
        proxy_pass http://sip-backend:5000/api/;
    }

    # existing API location (direct access)
    location /api/ {
        proxy_pass http://sip-backend:5000/api/;
    }
}
